import prettier from 'prettier'
import {
  InputData,
  jsonInputForTargetLanguage,
  JSONSourceData,
  quicktype,
} from 'quicktype-core'

export const quicktypeToTypeScript = async (source: JSONSourceData<string>) => {
  const jsonInput = jsonInputForTargetLanguage('ts')

  await jsonInput.addSource(source)

  const inputData = new InputData()
  inputData.addInput(jsonInput)

  const result = await quicktype({
    lang: 'ts',
    indentation: '  ',
    rendererOptions: {
      'just-types': true,
      'prefer-unions': true,
    },
    inputData,
    inferEnums: true,
  })

  const joined = result.lines.join('\n')
  const formatted = `/* GENERATED BY quicktype.ts, DO NOT EDIT */
/* eslint-disable */
namespace ${source.name} {
  ${joined}
}`
  const linted = prettier.format(formatted, { parser: 'typescript' })
  return linted
}
